apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintech-workload-sa
  namespace: fintech-platform
  annotations:
    iam.gke.io/gcp-service-account: fintech-gke-sa@fintech-data-hub-45513.iam.gserviceaccount.com
