apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fintechdatahub-connect-webapp-deployment
  minReplicas: 2   # Numero minimo di pod
  maxReplicas: 5   # Numero massimo di pod
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scalerà se l'uso medio di CPU supera il 70%
