server:
  port: 8081

spring:
  application:
    name: fintechdatahub-connect-rest

gcp:
  project-id: ${GCP_PROJECT_ID:still-nebula-505112-m8}
  datastore:
    database-id: ${GCP_DATASTORE_DATABASE_ID:fintechdatahub-connect-fs}
    namespace: ${GCP_DATASTORE_NAMESPACE:}
    import-on-startup: ${IMPORT_ON_STARTUP:true}

data:
  file:
    path: ${DATA_FILE_PATH:classpath:data/sample-data.json}
