steps:
  # 1. Maven Unit Tests (Verifica della qualita' del codice Java)
  - name: 'maven:3.9-eclipse-temurin-17'
    id: 'maven-test'
    entrypoint: 'mvn'
    args: ['test']
    dir: 'fintechdatahub-connect'

  # 2. Skaffold Build & Push su Google Artifact Registry
  - name: 'gcr.io/k8s-skaffold/skaffold:latest'
    id: 'skaffold-build'
    entrypoint: 'skaffold'
    args:
      - 'build'
      - '--file-output=artifacts.json'
      - '--default-repo=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}'
      - '--interactive=false'
    dir: 'fintechdatahub-connect'

  # 3. Creazione Release e Trigger Deploy automatico su Google Cloud Deploy (Formato Data/Ora: release-YYYYMMDD-HHMM)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'cloud-deploy-release'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RELEASE_NAME="release-$(TZ='Europe/Rome' date +'%Y%m%d-%H%M')"
        echo "Creazione release con nome: $${RELEASE_NAME}"
        gcloud deploy releases create "$${RELEASE_NAME}" \
          --delivery-pipeline=${_PIPELINE_NAME} \
          --region=${_REGION} \
          --build-artifacts=artifacts.json
    dir: 'fintechdatahub-connect'

# Utilizza il Service Account personalizzato dedicato
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/gke-node-sa@${PROJECT_ID}.iam.gserviceaccount.com'

substitutions:
  _REGION: 'europe-west8'
  _REPOSITORY: 'fdh-connect-registry'
  _PIPELINE_NAME: 'fintechdatahub-connect'

# Salva il file artifacts.json in modo permanente su Cloud Storage (GCS) alla fine della build
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/builds/$BUILD_ID'
    paths:
      - 'fintechdatahub-connect/artifacts.json'

options:
  logging: CLOUD_LOGGING_ONLY




