apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: fintechdatahub-connect

build:
  artifacts:
    - image: fintechdatahub-connect-rest
      context: .
      docker:
        dockerfile: fintechdatahub-connect-rest/Dockerfile
      sync:
        manual:
          - src: 'fintechdatahub-connect-rest/target/classes/**/*.class'
            dest: '/app/BOOT-INF/classes'
          - src: 'fintechdatahub-connect-rest/target/classes/**/*.yml'
            dest: '/app/BOOT-INF/classes'
    - image: fintechdatahub-connect-webapp
      context: .
      docker:
        dockerfile: fintechdatahub-connect-webapp/Dockerfile
      sync:
        manual:
          - src: 'fintechdatahub-connect-webapp/target/classes/**/*.class'
            dest: '/app/BOOT-INF/classes'
          - src: 'fintechdatahub-connect-webapp/target/classes/**/*.yml'
            dest: '/app/BOOT-INF/classes'
  googleCloudBuild:
    projectId: still-nebula-505112-m8
    serviceAccount: projects/still-nebula-505112-m8/serviceAccounts/gke-node-sa@still-nebula-505112-m8.iam.gserviceaccount.com
    region: europe-west8

# Profilo Predefinito: Sviluppo Locale su Minikube
manifests:
  kustomize:
    paths:
      - k8s/overlays/local

portForward:
  - resourceType: service
    resourceName: fintechdatahub-connect-webapp-service
    namespace: web-app
    port: 8080
    localPort: 8080

profiles:
  # 1. Profilo Locale Minikube (esplicito) -> skaffold dev --profile=local
  - name: local
    activation:
      - kubeContext: minikube
    build:
      local:
        push: false
    manifests:
      kustomize:
        paths:
          - k8s/overlays/local

  # 2. Profilo GCP TEST (Cloud Deploy / GKE Test)
  - name: test
    manifests:
      kustomize:
        paths:
          - k8s/overlays/test
    verify:
      - name: smoke-test-webapp
        container:
          name: curl-check
          image: curlimages/curl:latest
          args: ["-f", "http://fintechdatahub-connect-webapp-service.web-app:8080/"]
        executionMode:
          kubernetesCluster:
            overrides: '{"metadata": {"namespace": "web-app"}}'

  # 3. Profilo GCP STAGING (Cloud Deploy / GKE Staging)
  - name: staging
    manifests:
      kustomize:
        paths:
          - k8s/overlays/staging
    verify:
      - name: smoke-test-webapp
        container:
          name: curl-check
          image: curlimages/curl:latest
          args: ["-f", "http://fintechdatahub-connect-webapp-service.web-app:8080/"]
        executionMode:
          kubernetesCluster:
            overrides: '{"metadata": {"namespace": "web-app"}}'

  # 4. Profilo GCP PROD (Cloud Deploy / GKE Prod)
  - name: prod
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod
    verify:
      - name: smoke-test-webapp
        container:
          name: curl-check
          image: curlimages/curl:latest
          args: ["-f", "http://fintechdatahub-connect-webapp-service.web-app:8080/"]
        executionMode:
          kubernetesCluster:
            overrides: '{"metadata": {"namespace": "web-app"}}'
