apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-app

resources:
  - rest.yaml
  - webapp.yaml
  - ingress-setup.yaml
  - webapp-configmap.yaml
  - web-app-namespace.yaml
