apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintechdatahub-connect-webapp-deployment
  labels:
    app: fintechdatahub-connect-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintechdatahub-connect-webapp
  template:
    metadata:
      labels:
        app: fintechdatahub-connect-webapp
    spec:
      containers:
        - name: fintechdatahub-connect-webapp
          image: fintechdatahub-connect-webapp
          ports:
            - containerPort: 8080
          env:
            - name: REST_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: webapp-configmap
                  key: REST_SERVICE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
