apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintech-platform

resources:
- ../../base

labels:
- pairs:
    env: production

patches:
- path: patch-spot-nodes.yaml
  target:
    kind: Deployment
